language: python
dist: xenial
python: 3.6
compiler: gcc
matrix:
  include:
    - python: 3.7
      env:
      - TOX_ENV=py37
    - python: 3.8
      env:
      - TOX_ENV=py38
    - python: 3.9-dev
      env:
      - TOX_ENV=py39
env:
 - TOX_ENV=py36
 - TOX_ENV=flake8
install:
 - pip install tox
script:
 - tox -e $TOX_ENV